/**
 * Parse resource file generated by ResDepot
 *
 * Created by alexgan on 2015/5/18.
 *
 *
 * Usage:
 * Editing resouce groups configuration in ResDepot, then find the
 * group by [resGroup.groupName] in code.
 *
 * Caution:
 * Scene, Node, Plist, Tmx/Png...file should be included in preload before
 * starting a new scene.
 *
 * More details please visit: http://www.egret-labs.org/resdepot
 *
 */

var res;
var resGroup;
var resPath = "res/";

var stringRes = StringResParser.GetInstance();

function loadResources(lang) {
    var configFile = cc.path.join(resPath, "resource-" + lang + ".json");
    var config = JSON.parse(Util.readTxtFileSync(configFile));

    res = res || {};
    var resources = config.resources;
    for (var i in resources) {
        var name = resources[i].name;
        var url = resources[i].url;
        res[name] = resPath + url;
    }

    resGroup = resGroup || {};
    var groups = config.groups;
    for (var i in groups) {
        var name = groups[i].name;
        var group = [];
        var keysArr = groups[i].keys.split(",");
        for (var j in keysArr) {
            var value = res[keysArr[j]];
            group.push(value);
        }
        resGroup[name] = group;
    }

    // Load string resource
    stringRes.parse(Util.readTxtFileSync(res.ClientString_json));
}

(function () {
    // Read resources.json
    var lang = "zh";//cc.sys.localStorage.getItem("Language") || cc.sys.language;
    loadResources(lang);
})();