<?xml version="1.0" encoding="UTF-8"?>

<!-- 
    Filename: JSListCreate.xml
    Update time: 2016/5/23
    Author: alexgan
    Describe: 
-->

<project name="JSListCreate" default="file" basedir=".">
<property name="srcPath" value="./project.json"/>
<property name="desPath" value="./src/jsList.js"/>

<target name="createJSList">
  <delete file="${desPath}" failonerror="true"/>
  <copy file="${srcPath}" tofile="${desPath}" />

  <echo>Modify jsList.js content</echo>
  <replaceregexp  byline="false">
  <regexp pattern="([^..]*)&quot;jsLis" />  
  <substitution expression=""/>
  <fileset file="${desPath}"/>
  </replaceregexp>
  
  <replaceregexp  byline="false">
  <regexp pattern="(.*)}" />  
  <substitution expression=""/>  
  <fileset file="${desPath}"/>
  </replaceregexp>  
  
  <replaceregexp  byline="false">
  <regexp pattern="(.*)]" />  
  <substitution expression="];"/>  
  <fileset file="${desPath}"/>
  </replaceregexp>
  
  <echo>Remove 6 items in jsList.js</echo>
  
  <replaceregexp  byline="false">
  <regexp pattern="(.*)&quot;src/utils/Util.js&quot;," />  
  <substitution expression=""/>
  <fileset file="${desPath}"/>
  </replaceregexp>  
  
  <replaceregexp  byline="false">
  <regexp pattern="(.*)&quot;src/utils/StringResParser.js&quot;," />  
  <substitution expression=""/>
  <fileset file="${desPath}"/>
  </replaceregexp>  
  
  <replaceregexp  byline="false">
  <regexp pattern="(.*)&quot;src/resource.js&quot;," />  
  <substitution expression=""/>
  <fileset file="${desPath}"/>
  </replaceregexp>  
  
  <replaceregexp  byline="false">
  <regexp pattern="(.*)&quot;src/common/Common.js&quot;," />  
  <substitution expression=""/>
  <fileset file="${desPath}"/>
  </replaceregexp>  
  
  <replaceregexp  byline="false">
  <regexp pattern="(.*)&quot;src/gui/UIHelper.js&quot;," />  
  <substitution expression=""/>
  <fileset file="${desPath}"/>
  </replaceregexp>  
  
  <replaceregexp  byline="false">
  <regexp pattern="(.*)&quot;src/AssetsManager.js&quot;," />  
  <substitution expression=""/>
  <fileset file="${desPath}"/>
  </replaceregexp>  
  
  <echo>Write to jsList.js</echo>
  <replaceregexp  byline="false">
  <regexp pattern="t&quot;:" />  
  <substitution expression="/**&#10;
* Created by alexgan on 2016/5/23.&#10;
*&#10;
* Attention: # This file is automatically generated by tools.&#10;
*            # Do not modify this file -- YOUR CHANGES WILL BE ERASED!&#10;
*/&#10;
&#10;var jsList ="/>  
  <fileset file="${desPath}"/>
  </replaceregexp>

  <replaceregexp file="${desPath}"
                 match="(\r?\n)\s*\r?\n"
                 flags="g"
                 replace="\1" />

  <echo>Write to project.json</echo>
  <replaceregexp  byline="true">
  <regexp pattern="(.*).js&quot;,"/>  
  <substitution expression=""/>  
  <fileset file="${srcPath}"/>
  </replaceregexp>
  
  <replaceregexp  byline="true">
  <regexp pattern="(.*).js&quot;"/>
  <substitution expression="
   &quot;src/utils/Util.js&quot;,&#10;
   &quot;src/utils/StringResParser.js&quot;,&#10;
   &quot;src/resource.js&quot;,&#10;
   &quot;src/common/Common.js&quot;,&#10;
   &quot;src/gui/UIHelper.js&quot;,&#10;
   &quot;src/AssetsManager.js&quot;"/>
  <fileset file="${srcPath}"/>
  </replaceregexp>

  <replaceregexp file="${srcPath}"
               match="(\r?\n)\s*\r?\n" 
               flags="g"
               replace="\1" />
</target>
</project>